from __future__ import annotations

import re
from pathlib import Path

from .cythonizer import CythonUnit
from .errors import BuildError


def _c_string(value: str) -> str:
    pieces = []
    for byte in value.encode("utf-8"):
        if 32 <= byte <= 126 and byte not in {34, 92}:
            pieces.append(chr(byte))
        elif byte == 34:
            pieces.append(r'\"')
        elif byte == 92:
            pieces.append(r"\\")
        else:
            pieces.append(f"\\{byte:03o}")
    return '"' + "".join(pieces) + '"'


def write_launcher(
    path: Path,
    *,
    units: list[CythonUnit],
    entry_module: str,
    entry_callable: str | None,
    namespace_packages: tuple[str, ...],
    pack_symbols: list[str],
    resources: list[dict],
    windowed: bool,
) -> Path:
    by_name = {unit.module.name: unit for unit in units}
    entry = by_name.get(entry_module)
    if entry is None:
        raise BuildError(f"entry module {entry_module!r} was not Cythonized")
    if entry.main_flag is None:
        raise BuildError(f"Cython did not expose a main-module flag for {entry_module!r}")

    init_externs = [f"extern PyObject *{unit.init_symbol}(void);" for unit in units]
    init_externs.append(f"extern int {entry.main_flag};")
    builtin_entries = [
        f"    {{{_c_string(unit.module.name)}, {unit.init_symbol}}},"
        for unit in units
    ]
    if entry_module != "__main__":
        builtin_entries.append(f'    {{"__main__", {entry.init_symbol}}},')
    resource_externs = [f"extern const unsigned char {record['symbol']}[];" for record in resources]
    resource_entries = [
        "    {"
        f"{_c_string(record['target'])}, NULL, NULL, {record['symbol']}, "
        f"{record['compressed_size']}, {record['size']}, STATICPYTHON_RESOURCE_ZLIB"
        "},"
        for record in resources
    ]
    descriptor_externs = [f"extern const StaticPythonPackV1 {symbol};" for symbol in pack_symbols]
    selected_packs = ["    &StaticPython_BaseResourcePackV1,", *[f"    &{symbol}," for symbol in pack_symbols], "    &pysuture_application_pack,"]
    namespace_lines = [
        f"    if (pysuture_install_namespace({_c_string(name)}) < 0) return -1;"
        for name in namespace_packages
    ]
    callable_literal = "NULL" if entry_callable is None else _c_string(entry_callable)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "/* Auto-generated by PySuture. SPDX-License-Identifier: Apache-2.0 */\n"
        "#define PY_SSIZE_T_CLEAN\n"
        "#include \"Python.h\"\n"
        "#include \"staticpython_pack.h\"\n"
        "#include <windows.h>\n"
        "#include <limits.h>\n"
        "#include <shellapi.h>\n"
        "#include <wchar.h>\n\n"
        + "\n".join(init_externs + resource_externs + descriptor_externs)
        + "\n\n"
        + "static const StaticPythonBuiltinModuleV1 pysuture_builtin_modules[] = {\n"
        + "\n".join(builtin_entries)
        + "\n};\n\n"
        + "static const StaticPythonResourceV1 pysuture_resources[] = {\n"
        + ("\n".join(resource_entries) if resource_entries else "    {0},")
        + "\n};\n\n"
        + "static const StaticPythonPackV1 pysuture_application_pack = {\n"
        + "    sizeof(StaticPythonPackV1),\n"
        + "    STATICPYTHON_PACK_ABI_VERSION,\n"
        + "    \"pysuture-application\",\n"
        + "    \"1\",\n"
        + "    \"cp\" Py_STRINGIFY(PY_MAJOR_VERSION) Py_STRINGIFY(PY_MINOR_VERSION),\n"
        + "    NULL, 0,\n"
        + f"    pysuture_builtin_modules, {len(builtin_entries)},\n"
        + f"    pysuture_resources, {len(resource_entries)},\n"
        + "    NULL, 0,\n"
        + "    NULL, 0,\n"
        + "    NULL, 0,\n"
        + "    NULL\n"
        + "};\n\n"
        + "static const StaticPythonPackV1 *const pysuture_packs[] = {\n"
        + "\n".join(selected_packs)
        + "\n};\n\n"
        + f"static const int pysuture_windowed = {1 if windowed else 0};\n\n"
        + "static void\n"
        + "pysuture_show_error(const wchar_t *fallback)\n"
        + "{\n"
        + "    if (!PyErr_Occurred()) {\n"
        + "        if (pysuture_windowed) MessageBoxW(NULL, fallback, L\"PySuture application error\", MB_OK | MB_ICONERROR);\n"
        + "        return;\n"
        + "    }\n"
        + "    if (!pysuture_windowed) {\n"
        + "        PyErr_Print();\n"
        + "        return;\n"
        + "    }\n"
        + "    PyObject *type = NULL, *value = NULL, *traceback = NULL;\n"
        + "    PyErr_Fetch(&type, &value, &traceback);\n"
        + "    PyErr_NormalizeException(&type, &value, &traceback);\n"
        + "    PyObject *text = value != NULL ? PyObject_Str(value) : NULL;\n"
        + "    const wchar_t *message = text != NULL ? PyUnicode_AsWideCharString(text, NULL) : NULL;\n"
        + "    MessageBoxW(NULL, message != NULL ? message : fallback, L\"PySuture application error\", MB_OK | MB_ICONERROR);\n"
        + "    if (message != NULL) PyMem_Free((void *)message);\n"
        + "    Py_XDECREF(text);\n"
        + "    Py_XDECREF(type); Py_XDECREF(value); Py_XDECREF(traceback);\n"
        + "}\n\n"
        + "static int\n"
        + "pysuture_system_exit_code(void)\n"
        + "{\n"
        + "    PyObject *type = NULL, *value = NULL, *traceback = NULL;\n"
        + "    if (!PyErr_ExceptionMatches(PyExc_SystemExit)) return -1;\n"
        + "    PyErr_Fetch(&type, &value, &traceback);\n"
        + "    PyErr_NormalizeException(&type, &value, &traceback);\n"
        + "    int result = 0;\n"
        + "    PyObject *code = value != NULL ? PyObject_GetAttrString(value, \"code\") : NULL;\n"
        + "    if (code != NULL && code != Py_None) {\n"
        + "        if (PyLong_Check(code)) {\n"
        + "            long numeric = PyLong_AsLong(code);\n"
        + "            result = numeric < 0 ? 1 : (numeric > 255 ? 255 : (int)numeric);\n"
        + "        } else {\n"
        + "            PyObject *text = PyObject_Str(code);\n"
        + "            if (text != NULL) {\n"
        + "                PyObject_Print(text, stderr, Py_PRINT_RAW);\n"
        + "                fputc('\\n', stderr);\n"
        + "                Py_DECREF(text);\n"
        + "            }\n"
        + "            result = 1;\n"
        + "        }\n"
        + "    }\n"
        + "    Py_XDECREF(code); Py_XDECREF(type); Py_XDECREF(value); Py_XDECREF(traceback);\n"
        + "    PyErr_Clear();\n"
        + "    return result;\n"
        + "}\n\n"
        + "static int\n"
        + "pysuture_install_namespace(const char *name)\n"
        + "{\n"
        + "    PyObject *modules = PyImport_GetModuleDict();\n"
        + "    if (PyDict_GetItemString(modules, name) != NULL) return 0;\n"
        + "    PyObject *module = PyModule_New(name);\n"
        + "    PyObject *path = PyList_New(0);\n"
        + "    if (module == NULL || path == NULL) { Py_XDECREF(module); Py_XDECREF(path); return -1; }\n"
        + "    if (PyModule_AddObjectRef(module, \"__path__\", path) < 0\n"
        + "        || PyModule_AddStringConstant(module, \"__package__\", name) < 0\n"
        + "        || PyDict_SetItemString(modules, name, module) < 0) {\n"
        + "        Py_DECREF(path); Py_DECREF(module); return -1;\n"
        + "    }\n"
        + "    Py_DECREF(path); Py_DECREF(module); return 0;\n"
        + "}\n\n"
        + "static PyObject *\n"
        + "pysuture_import_callable(const char *module_name, const char *callable_name)\n"
        + "{\n"
        + "    PyObject *module = PyImport_ImportModule(module_name);\n"
        + "    if (module == NULL) return NULL;\n"
        + "    PyObject *callable = PyObject_GetAttrString(module, callable_name);\n"
        + "    Py_DECREF(module);\n"
        + "    if (callable == NULL) return NULL;\n"
        + "    PyObject *result = PyObject_CallNoArgs(callable);\n"
        + "    Py_DECREF(callable);\n"
        + "    return result;\n"
        + "}\n\n"
        + "static int\n"
        + "pysuture_has_decimal_argument(const wchar_t *argument, const wchar_t *prefix)\n"
        + "{\n"
        + "    size_t prefix_length = wcslen(prefix);\n"
        + "    if (wcsncmp(argument, prefix, prefix_length) != 0) return 0;\n"
        + "    const wchar_t *cursor = argument + prefix_length;\n"
        + "    if (*cursor == L'\\0') return 0;\n"
        + "    unsigned long long value = 0;\n"
        + "    while (*cursor != L'\\0') {\n"
        + "        if (*cursor < L'0' || *cursor > L'9') return 0;\n"
        + "        int digit = (int)(*cursor - L'0');\n"
        + "        if (value > (ULLONG_MAX - (unsigned long long)digit) / 10) return 0;\n"
        + "        value = value * 10 + (unsigned long long)digit;\n"
        + "        cursor++;\n"
        + "    }\n"
        + "    return 1;\n"
        + "}\n\n"
        + "static int\n"
        + "pysuture_is_multiprocessing_fork(int argc, wchar_t **argv)\n"
        + "{\n"
        + "    return argc == 4\n"
        + "        && wcscmp(argv[1], L\"--multiprocessing-fork\") == 0\n"
        + "        && pysuture_has_decimal_argument(argv[2], L\"parent_pid=\")\n"
        + "        && pysuture_has_decimal_argument(argv[3], L\"pipe_handle=\");\n"
        + "}\n\n"
        + "static int\n"
        + "pysuture_is_resource_tracker(int argc, wchar_t **argv, long long *fd)\n"
        + "{\n"
        + "    if (argc != 3 || wcscmp(argv[1], L\"-c\") != 0) return 0;\n"
        + "    const wchar_t *prefix = L\"from multiprocessing.resource_tracker import main;main(\";\n"
        + "    size_t prefix_length = wcslen(prefix);\n"
        + "    if (wcsncmp(argv[2], prefix, prefix_length) != 0) return 0;\n"
        + "    const wchar_t *number = argv[2] + prefix_length;\n"
        + "    if (*number == L'\\0') return 0;\n"
        + "    long long value = 0;\n"
        + "    const wchar_t *cursor = number;\n"
        + "    while (*cursor >= L'0' && *cursor <= L'9') {\n"
        + "        int digit = (int)(*cursor - L'0');\n"
        + "        if (value > (LLONG_MAX - digit) / 10) return 0;\n"
        + "        value = value * 10 + digit;\n"
        + "        cursor++;\n"
        + "    }\n"
        + "    if (cursor == number || cursor[0] != L')' || cursor[1] != L'\\0') return 0;\n"
        + "    *fd = value;\n"
        + "    return 1;\n"
        + "}\n\n"
        + "static int\n"
        + "pysuture_dispatch_multiprocessing(int argc, wchar_t **argv)\n"
        + "{\n"
        + "    if (pysuture_is_multiprocessing_fork(argc, argv)) {\n"
        + "        PyObject *result = pysuture_import_callable(\"multiprocessing.spawn\", \"freeze_support\");\n"
        + "        if (result == NULL) { int code = pysuture_system_exit_code(); if (code >= 0) return code; return -1; }\n"
        + "        Py_DECREF(result); return 0;\n"
        + "    }\n"
        + "    long long tracker_fd = 0;\n"
        + "    if (pysuture_is_resource_tracker(argc, argv, &tracker_fd)) {\n"
        + "        PyObject *module = PyImport_ImportModule(\"multiprocessing.resource_tracker\");\n"
        + "        PyObject *main = module != NULL ? PyObject_GetAttrString(module, \"main\") : NULL;\n"
        + "        PyObject *argument = PyLong_FromLongLong(tracker_fd);\n"
        + "        PyObject *result = main != NULL && argument != NULL ? PyObject_CallOneArg(main, argument) : NULL;\n"
        + "        Py_XDECREF(argument); Py_XDECREF(main); Py_XDECREF(module);\n"
        + "        if (result == NULL) { int code = pysuture_system_exit_code(); if (code >= 0) return code; return -1; }\n"
        + "        Py_DECREF(result); return 0;\n"
        + "    }\n"
        + "    return -2;\n"
        + "}\n\n"
        + "static int\n"
        + "pysuture_run(int argc, wchar_t **argv)\n"
        + "{\n"
        + "    if (StaticPython_RegisterPacks(pysuture_packs, sizeof(pysuture_packs) / sizeof(pysuture_packs[0])) < 0) {\n"
        + "        wchar_t message[600];\n"
        + "        MultiByteToWideChar(CP_UTF8, 0, StaticPython_LastError(), -1, message, 600);\n"
        + "        if (pysuture_windowed) MessageBoxW(NULL, message, L\"PySuture startup error\", MB_OK | MB_ICONERROR);\n"
        + "        else fwprintf(stderr, L\"PySuture startup error: %ls\\n\", message);\n"
        + "        return 120;\n"
        + "    }\n"
        + "    PyStatus status;\n"
        + "    PyConfig config;\n"
        + "    PyConfig_InitIsolatedConfig(&config);\n"
        + "    config.parse_argv = 0;\n"
        + "    config.use_environment = 0;\n"
        + "    config.user_site_directory = 0;\n"
        + "    config.safe_path = 1;\n"
        + "    config.write_bytecode = 0;\n"
        + "    config.pathconfig_warnings = 0;\n"
        + "    config.site_import = 1;\n"
        + "    config.module_search_paths_set = 1;\n"
        + "    status = PyWideStringList_Append(&config.module_search_paths, L\"pysuture://embedded\");\n"
        + "    if (!PyStatus_Exception(status)) status = PyConfig_SetString(&config, &config.stdio_encoding, L\"utf-8\");\n"
        + "    if (!PyStatus_Exception(status)) status = PyConfig_SetString(&config, &config.stdio_errors, L\"strict\");\n"
        + "    if (!PyStatus_Exception(status)) status = PyConfig_SetArgv(&config, argc, argv);\n"
        + "    if (!PyStatus_Exception(status)) status = PyConfig_SetString(&config, &config.program_name, argv[0]);\n"
        + "    if (!PyStatus_Exception(status)) status = PyConfig_SetString(&config, &config.executable, argv[0]);\n"
        + "    if (PyStatus_Exception(status)) { PyConfig_Clear(&config); Py_ExitStatusException(status); }\n"
        + "    status = Py_InitializeFromConfig(&config);\n"
        + "    PyConfig_Clear(&config);\n"
        + "    if (PyStatus_Exception(status)) Py_ExitStatusException(status);\n"
        + "    PyObject *sys = PyImport_ImportModule(\"sys\");\n"
        + "    if (sys == NULL || PyObject_SetAttrString(sys, \"frozen\", Py_True) < 0) {\n"
        + "        Py_XDECREF(sys); pysuture_show_error(L\"Could not initialize sys.frozen\"); return 121;\n"
        + "    }\n"
        + "    Py_DECREF(sys);\n"
        + "    PyObject *runtime = PyImport_ImportModule(\"_staticpython_runtime\");\n"
        + "    PyObject *installed = runtime != NULL ? PyObject_CallMethod(runtime, \"install\", NULL) : NULL;\n"
        + "    Py_XDECREF(installed); Py_XDECREF(runtime);\n"
        + "    if (PyErr_Occurred()) { pysuture_show_error(L\"Could not install embedded resources\"); return 122; }\n"
        + "    int multiprocessing = pysuture_dispatch_multiprocessing(argc, argv);\n"
        + "    if (multiprocessing >= 0) { Py_FinalizeEx(); return multiprocessing; }\n"
        + "    if (multiprocessing == -1) { pysuture_show_error(L\"Multiprocessing child startup failed\"); Py_FinalizeEx(); return 123; }\n"
        + ("\n".join(namespace_lines) + "\n" if namespace_lines else "")
        + f"    {entry.main_flag} = 1;\n"
        + "    PyObject *modules = PyImport_GetModuleDict();\n"
        + "    if (PyDict_DelItemString(modules, \"__main__\") < 0) PyErr_Clear();\n"
        + "    PyObject *main_module = PyImport_ImportModule(\"__main__\");\n"
        + "    if (main_module == NULL) {\n"
        + "        int code = pysuture_system_exit_code();\n"
        + "        if (code < 0) { pysuture_show_error(L\"Application import failed\"); code = 1; }\n"
        + "        Py_FinalizeEx(); return code;\n"
        + "    }\n"
        + f"    if (PyDict_SetItemString(modules, {_c_string(entry_module)}, main_module) < 0) {{\n"
        + "        Py_DECREF(main_module); pysuture_show_error(L\"Could not alias the entry module\"); Py_FinalizeEx(); return 1;\n"
        + "    }\n"
        + f"    const char *entry_callable = {callable_literal};\n"
        + "    int exit_code = 0;\n"
        + "    if (entry_callable != NULL) {\n"
        + "        PyObject *callable = PyObject_GetAttrString(main_module, entry_callable);\n"
        + "        PyObject *result = callable != NULL ? PyObject_CallNoArgs(callable) : NULL;\n"
        + "        Py_XDECREF(callable);\n"
        + "        if (result == NULL) {\n"
        + "            exit_code = pysuture_system_exit_code();\n"
        + "            if (exit_code < 0) { pysuture_show_error(L\"Application entry callable failed\"); exit_code = 1; }\n"
        + "        } else {\n"
        + "            if (PyLong_Check(result)) { long value = PyLong_AsLong(result); exit_code = value < 0 ? 1 : (value > 255 ? 255 : (int)value); }\n"
        + "            Py_DECREF(result);\n"
        + "        }\n"
        + "    }\n"
        + "    Py_DECREF(main_module);\n"
        + "    if (Py_FinalizeEx() < 0 && exit_code == 0) exit_code = 120;\n"
        + "    return exit_code;\n"
        + "}\n\n"
        + ("int WINAPI\nwWinMain(HINSTANCE instance, HINSTANCE previous, PWSTR command_line, int show_command)\n{\n    (void)instance; (void)previous; (void)command_line; (void)show_command;\n    int argc = 0;\n    wchar_t **argv = CommandLineToArgvW(GetCommandLineW(), &argc);\n    if (argv == NULL) return 120;\n    int result = pysuture_run(argc, argv);\n    LocalFree(argv);\n    return result;\n}\n" if windowed else "int\nwmain(int argc, wchar_t **argv)\n{\n    return pysuture_run(argc, argv);\n}\n"),
        encoding="utf-8",
        newline="\n",
    )
    return path
