from __future__ import annotations

import glob
import hashlib
import os
import re
import zlib
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from .config import ProjectConfig
from .constants import SECRET_BASENAMES, SECRET_SUFFIXES
from .errors import BuildError


@dataclass(frozen=True)
class ResourceRecord:
    source: Path
    target: str
    sha256: str
    size: int


def _wildcard_anchor(pattern: str) -> Path:
    parts = Path(pattern).parts
    stable = []
    for part in parts:
        if any(character in part for character in "*?["):
            break
        stable.append(part)
    return Path(*stable) if stable else Path(".")


def _safe_target(value: str) -> str:
    normalized = value.replace("\\", "/").strip("/")
    path = PurePosixPath(normalized)
    if not normalized or path.is_absolute() or ".." in path.parts:
        raise BuildError(f"resource target must be a safe relative virtual path: {value!r}")
    return path.as_posix()


def _looks_secret(path: Path) -> bool:
    name = path.name.casefold()
    return name in SECRET_BASENAMES or path.suffix.casefold() in SECRET_SUFFIXES


def collect_application_resources(config: ProjectConfig) -> tuple[list[ResourceRecord], list[str]]:
    root = config.root.resolve()
    records: dict[str, ResourceRecord] = {}
    warnings: list[str] = []
    for mapping in config.data:
        pattern = mapping.source.replace("\\", "/")
        absolute_pattern = str(root / Path(pattern))
        matches = sorted(Path(value) for value in glob.glob(absolute_pattern, recursive=True))
        files = [path for path in matches if path.is_file()]
        if not files:
            raise BuildError(f"resource include pattern matched no files: {mapping.source}")
        anchor = (root / _wildcard_anchor(pattern)).resolve()
        has_wildcard = any(character in pattern for character in "*?[")
        for path in files:
            resolved = path.resolve()
            if root != resolved and root not in resolved.parents:
                raise BuildError(f"resource escapes the project root: {path}")
            if _looks_secret(resolved):
                message = f"resource looks like a credential or private key: {resolved.relative_to(root)}"
                if config.secret_policy == "error":
                    raise BuildError(message)
                if config.secret_policy == "warn":
                    warnings.append(message)
            if has_wildcard:
                try:
                    suffix = resolved.relative_to(anchor).as_posix()
                except ValueError as exc:
                    raise BuildError(f"resource {resolved} is outside wildcard anchor {anchor}") from exc
                target = _safe_target(f"{mapping.target.rstrip('/')}/{suffix}")
            else:
                target_value = mapping.target
                if target_value.endswith(("/", "\\")):
                    target_value += resolved.name
                target = _safe_target(target_value)
            if target in records:
                raise BuildError(f"multiple resources map to virtual path {target!r}")
            payload = resolved.read_bytes()
            records[target] = ResourceRecord(
                source=resolved,
                target=target,
                sha256=hashlib.sha256(payload).hexdigest(),
                size=len(payload),
            )
    return [records[name] for name in sorted(records)], warnings


def write_resource_sources(records: list[ResourceRecord], source_dir: Path) -> list[dict]:
    source_dir.mkdir(parents=True, exist_ok=True)
    generated: list[dict] = []
    for index, record in enumerate(records, start=1):
        payload = record.source.read_bytes()
        compressed = zlib.compress(payload, level=9)
        symbol = f"pysuture_resource_{index:06d}_{record.sha256[:16]}"
        values = [str(value) for value in compressed]
        rows = ["    " + ", ".join(values[offset : offset + 24]) + "," for offset in range(0, len(values), 24)]
        path = source_dir / f"resource_{index:06d}.c"
        path.write_text(
            "/* Auto-generated by PySuture. SPDX-License-Identifier: Apache-2.0 */\n"
            "#include <stddef.h>\n\n"
            f"const unsigned char {symbol}[] = {{\n"
            + ("\n".join(rows) if rows else "    0,")
            + "\n};\n",
            encoding="utf-8",
            newline="\n",
        )
        generated.append(
            {
                "target": record.target,
                "source": str(path),
                "symbol": symbol,
                "size": len(payload),
                "compressed_size": len(compressed),
                "sha256": record.sha256,
            }
        )
    return generated
